//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string CarName { get; set; }
        public string Date { get; set; }
        public Nullable<int> Charges { get; set; }
    }
}
